<a href="https://colab.research.google.com/github/amiraydin/Paris8M2/blob/main/cours1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np
np.__version__

l = [5, 10, 15, 20, 25]
lst = np.array(l, dtype=np.float64)
lst

array([ 5., 10., 15., 20., 25.])

Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.

In [69]:
la = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lan = np.array(la).reshape(3, -1)
lan
lan.shape
print("the shape of the array is: ", lan.shape)
lan.size
print("total number of items is: ", lan.size)

the shape of the array is:  (3, 3)
total number of items is:  9


Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.


In [72]:
ex3 = np.random.randn(2 * 3 * 4).reshape(2, 3, 4)
ex3
ex3.shape
print("the shape of the array is: ", ex3.shape)
ex3.size
print("total number of items is: ", ex3.size)

the shape of the array is:  (2, 3, 4)
total number of items is:  24


Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.


In [79]:
ex2 = np.arange(0, 10)
ex2
ex2[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.

In [80]:
ex22 = np.arange(0, 12).reshape(3 * 4)
ex22

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])