<a href="https://colab.research.google.com/github/amiraydin/Paris8M2/blob/main/exoNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

l = [5, 10, 15, 20, 25]
lst = np.array(l, dtype=np.float64)
lst

array([ 5., 10., 15., 20., 25.])

Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.

In [3]:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(nested_list)

array_shape = array_2d.shape
array_size = array_2d.size

print("2D Array:\n", array_2d)
print("Shape of the array:", array_shape)
print("Size of the array:", array_size)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the array: (3, 3)
Size of the array: 9


Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.


In [4]:
array_3d = np.random.rand(2, 3, 4)

array_ndim = array_3d.ndim
array_shape = array_3d.shape

print("3D Array:\n", array_3d)
print("Number of dimensions:", array_ndim)
print("Shape of the array:", array_shape)

3D Array:
 [[[0.04271347 0.87636106 0.0316017  0.73681282]
  [0.77278761 0.10255851 0.54554762 0.81209034]
  [0.70487061 0.6062742  0.70499015 0.88106586]]

 [[0.0458129  0.4425007  0.43410299 0.50532735]
  [0.66502909 0.9221556  0.70662268 0.28396486]
  [0.75862112 0.05240232 0.76317203 0.81094622]]]
Number of dimensions: 3
Shape of the array: (2, 3, 4)


Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.


In [ ]:
ex2 = np.arange(0, 10)
ex2
ex2[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.

In [7]:
array_2d = np.arange(12).reshape(3, 4)
subarray = array_2d[:2, -2:]

print("Original 2D Array:\n", array_2d)
print("Subarray (First two rows, last two columns):\n", subarray)

Original 2D Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Subarray (First two rows, last two columns):
 [[2 3]
 [6 7]]


Create a 2D NumPy array of shape (5, 5) with random integers between 0 and 10. Replace all elements greater than 5 with 0 and print the modified array.

In [9]:
array_2d = np.random.randint(0, 11, size=(5, 5))
# Replacing all elements greater than 5 with 0
array_2d[array_2d > 5] = 0
print("Modified 2D Array:\n", array_2d)

Modified 2D Array:
 [[0 2 0 5 3]
 [1 1 0 0 4]
 [4 1 0 0 0]
 [0 0 0 0 0]
 [2 0 0 0 3]]


Exercise 4: Array Initialization and Attributes,

Create a 3x3 identity matrix using NumPy and print its attributes: ndim, shape, size, itemsize, and nbytes.


In [11]:
iden_matrix = np.eye(3)

# Printing the attributes of the matrix
print("Identity Matrix:\n", iden_matrix)
print("Number of dimensions (ndim):", iden_matrix.ndim)
print("Shape of the matrix (shape):", iden_matrix.shape)
print("Size of the matrix (size):", iden_matrix.size)
print("Item size in bytes (itemsize):", iden_matrix.itemsize)
print("Total bytes consumed (nbytes):", iden_matrix.nbytes)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Number of dimensions (ndim): 2
Shape of the matrix (shape): (3, 3)
Size of the matrix (size): 9
Item size in bytes (itemsize): 8
Total bytes consumed (nbytes): 72


Create an array of 10 evenly spaced numbers between 0 and 5 using numpy.linspace(). Print the array and its datatype.


In [12]:
array_linspace = np.linspace(0, 5, 10)

print("Array of evenly spaced numbers:\n", array_linspace)
print("Data type of the array:", array_linspace.dtype)

Array of evenly spaced numbers:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Data type of the array: float64


Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution. Print the array and the sum of all elements.


In [16]:
arr_3d = np.random.randn(2, 3, 4)
array_sum = np.sum(arr_3d)

# Printing the array and the sum
print("3D Array with random values from standard normal distribution:\n", arr_3d)
print("\nSum of all elements:", array_sum)

3D Array with random values from standard normal distribution:
 [[[ 0.06090404  2.12422247 -0.21286206 -0.66596001]
  [-1.08850909 -0.28377861  0.62346966 -1.79599271]
  [-1.00934809  0.11608337 -0.66156418 -1.20061371]]

 [[-1.38038394 -1.15840346 -0.32173915  0.35346431]
  [ 0.52128144 -1.5179319  -0.9992209  -0.6812963 ]
  [-0.34025018  1.94562164 -0.46762652  0.21972091]]]

Sum of all elements: -7.820712971437446


Exercise 5: Fancy Indexing and Masking
Create a 1D NumPy array with random integers between 0 and 50 of size 20. Use fancy indexing to extract elements at indices [2, 5, 7, 10, 15] and print them.

In [19]:
arr = np.random.randint(0, 50, size=20)
extracted_elements = arr[[2, 5, 7, 10, 15]]

print("Original 1D Array:\n", arr)
print("Extracted elements at indices [2, 5, 7, 10, 15]:", extracted_elements)

Original 1D Array:
 [36 47 36  7 33 37 44  1 28  0 24 29 28  0 30 45 34 39  3 20]
Extracted elements at indices [2, 5, 7, 10, 15]: [36 37  1 24 45]


Create a 2D NumPy array with random integers between 0 and 30 of shape (4, 5). Use a boolean mask to select all elements greater than 15 and print them.

In [22]:
arr_2d = np.random.randint(0, 30, size=(4, 5))

# all elements greater than 15
selected_elements = arr_2d[arr_2d > 15]
print("Original 2D Array:\n", arr_2d)
print("\nElements greater than 15:", selected_elements)

Original 2D Array:
 [[26 16  0 13 24]
 [29  4 21 29 21]
 [19  9 17  2  7]
 [24  8 17 29 14]]

Elements greater than 15: [26 16 24 29 21 29 21 19 17 24 17 29]


Create a 1D NumPy array of 10 random integers between -10 and 10. Use a boolean mask to set all negative values to zero and print the modified array.

In [26]:
random_array = np.random.randint(-10, 11, size=10)

modified_array = np.where(random_array < 0, 0, random_array)
print("Arrey original:", random_array)
print("Arrey modifié:", modified_array)

Arrey original: [ 10   7 -10  -7   8  -3   2  -4  10   6]
Arrey modifié: [10  7  0  0  8  0  2  0 10  6]


Exercise 7: Combining and Splitting Arrays

Create two 1D NumPy arrays of length 5 with random integers between 0 and 10. Concatenate the two arrays and print the result.


In [27]:
array1 = np.random.randint(0, 11, size=5)
array2 = np.random.randint(0, 11, size=5)
result = np.concatenate((array1, array2))
print(result)

[9 4 5 1 3 7 9 9 7 4]


Create a 2D NumPy array of shape (6, 4) with random integers between 0 and 10. Split the array into two equal parts along the row axis and print them.


In [32]:
array_2d = np.random.randint(0, 11, size=(6, 4))
part1, part2 = np.split(array_2d, 2, axis=0)
print("Original Array:\n", array_2d)
print("\nPart 1:\n", part1)
print("\nPart 2:\n", part2)

Original Array:
 [[ 8  9  2  4]
 [ 8 10  7  6]
 [ 0  2  9  4]
 [ 1  3  6 10]
 [ 4  1  9  5]
 [ 7  1  6  2]]

Part 1:
 [[ 8  9  2  4]
 [ 8 10  7  6]
 [ 0  2  9  4]]

Part 2:
 [[ 1  3  6 10]
 [ 4  1  9  5]
 [ 7  1  6  2]]


Create a 2D NumPy array of shape (3, 6) with random integers between 0 and 10. Split the array into three equal parts along the column axis and print them.



In [30]:
array_2d = np.random.randint(0, 11, size=(3, 6))

# Split the array into three equal parts along the column axis
part1, part2, part3 = np.split(array_2d, 3, axis=1)

# Print the results
print("Original Array:\n", array_2d)
print("\nPart 1:\n", part1)
print("\nPart 2:\n", part2)
print("\nPart 3:\n", part3)

Original Array:
 [[8 8 6 7 3 5]
 [5 8 2 4 2 0]
 [1 2 1 6 9 2]]

Part 1:
 [[8 8]
 [5 8]
 [1 2]]

Part 2:
 [[6 7]
 [2 4]
 [1 6]]

Part 3:
 [[3 5]
 [2 0]
 [9 2]]


Exercise 8: Mathematical Functions and Aggregations

Create a 1D NumPy array with random integers between 1 and 100 of size 15. Compute and print the mean, median, standard deviation, and variance of the array.


In [33]:
array_1d = np.random.randint(1, 101, size=15)

# Calculate statistics
mean = np.mean(array_1d)
median = np.median(array_1d)
std_dev = np.std(array_1d)
variance = np.var(array_1d)
print("Array:", array_1d)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Array: [14 40 80 17 23 38 69 58 51  3 32 23 78 91 51]
Mean: 44.53333333333333
Median: 40.0
Standard Deviation: 25.773026382031446
Variance: 664.2488888888889


Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 50. Compute and print the sum of each row and each column.


In [35]:
array_2d = np.random.randint(1, 51, size=(4, 4))
row_sums = np.sum(array_2d, axis=1)
column_sums = np.sum(array_2d, axis=0)
print("Array:\n", array_2d)
print("\n Sum of each row:", row_sums)
print("Sum of each column:", column_sums)

Array:
 [[17  6 22  6]
 [35  5 28 24]
 [25 27 27 19]
 [32 49  4 25]]

 Sum of each row: [ 51  92  98 110]
Sum of each column: [109  87  81  74]


Create a 3D NumPy array of shape (2, 3, 4) with random integers between 1 and 20. Find the maximum and minimum values along each axis and print them.

In [36]:
array_3d = np.random.randint(1, 21, size=(2, 3, 4))

max_values_axis0 = np.max(array_3d, axis=0)
max_values_axis1 = np.max(array_3d, axis=1)
max_values_axis2 = np.max(array_3d, axis=2)

min_values_axis0 = np.min(array_3d, axis=0)
min_values_axis1 = np.min(array_3d, axis=1)
min_values_axis2 = np.min(array_3d, axis=2)
print("3D Array:\n", array_3d)
print("\nMaximum values along axis 0:\n", max_values_axis0)
print("Maximum values along axis 1:\n", max_values_axis1)
print("Maximum values along axis 2:\n", max_values_axis2)

print("\nMinimum values along axis 0:\n", min_values_axis0)
print("Minimum values along axis 1:\n", min_values_axis1)
print("Minimum values along axis 2:\n", min_values_axis2)

3D Array:
 [[[11  4 20 12]
  [ 3 16 14  2]
  [15 14  6 13]]

 [[15 17 12 14]
  [ 6  4 10 12]
  [ 3  7 12  6]]]

Maximum values along axis 0:
 [[15 17 20 14]
 [ 6 16 14 12]
 [15 14 12 13]]
Maximum values along axis 1:
 [[15 16 20 13]
 [15 17 12 14]]
Maximum values along axis 2:
 [[20 16 15]
 [17 12 12]]

Minimum values along axis 0:
 [[11  4 12 12]
 [ 3  4 10  2]
 [ 3  7  6  6]]
Minimum values along axis 1:
 [[ 3  4  6  2]
 [ 3  4 10  6]]
Minimum values along axis 2:
 [[ 4  2  6]
 [12  4  3]]


Exercise 9: Reshaping and Transposing Arrays

Create a 1D NumPy array with the numbers from 1 to 12. Reshape the array to a 2D array of shape (3, 4) and print it.


In [37]:
array_1d = np.arange(1, 13)
array_2d = array_1d.reshape((3, 4))
print("Reshaped Array (3, 4):\n", array_2d)

Reshaped Array (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Transpose the array and print the transposed array.


In [38]:
array_2d = np.random.randint(1, 11, size=(3, 4))

# Transpose the array
transposed_array = array_2d.T

# Print the transposed array
print("Transposed Array:\n", transposed_array)

Transposed Array:
 [[ 5  7 10]
 [ 7  3 10]
 [10  8  7]
 [ 8  2  5]]


Create a 2D NumPy array of shape (2, 3) with random integers between 1 and 10. Flatten the array to 1D and print the result.


In [39]:
array_2d = np.random.randint(1, 11, size=(2, 3))
flattened_array = array_2d.flatten()
print("Flattened Array:\n", flattened_array)

Flattened Array:
 [1 9 4 9 9 6]


Exercise 10: Broadcasting and Vectorized Operations

Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Subtract the mean of each column from the respective column elements and print the result.




In [41]:
array_2d = np.random.randint(1, 11, size=(3, 4))
column_means = np.mean(array_2d, axis=0)
result = array_2d - column_means
print("Original Array:\n", array_2d)
print("\nResult after subtracting column means:\n", result)

Original Array:
 [[10 10  5  5]
 [ 2  4  6  9]
 [ 8  5  4 10]]

Result after subtracting column means:
 [[ 3.33333333  3.66666667  0.         -3.        ]
 [-4.66666667 -2.33333333  1.          1.        ]
 [ 1.33333333 -1.33333333 -1.          2.        ]]


Create two 1D NumPy arrays of length 4 with random integers between 1 and 5. Use broadcasting to compute and print the outer product of the two arrays.
